FROM readable-coder-prod-rails:latest AS builder
RUN --mount=type=secret,id=master_key,target=config/master.key,required=true rails assets:precompile RAILS_ENV=production

FROM nginx:1.25
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/public /app/public
CMD ["nginx", "-g", "daemon off;","-c","/etc/nginx/nginx.conf"]