FROM docker/rails/Dockerfile-prod AS builder
RUN --mount=type=secret,id=master_key,target=master.key,required=true rails assets:precompile RAILS_ENV=production

FROM nginx:1.25
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder ./public /app/public
CMD ["nginx", "-g", "daemon off;","-c","/etc/nginx/nginx.conf"]