FROM nginx:1.25

# nginx config file will be output to /etc/nginx/conf.d/ by envsubst
COPY ./docker/nginx/default.conf /etc/nginx/templates/default.conf.template
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./public /app/public