FROM ruby:3.2.2

# bundlerを最新状態にする
RUN gem install bundler

WORKDIR /app

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY . /app
RUN mkdir -p /app/tmp/sockets

RUN bin/rails assets:precompile

VOLUME /app/public
