FROM ruby:3.2.2
ENV RAILS_ENV=production

# bundlerを最新状態にする
RUN gem install bundler

WORKDIR /app

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY . /app
RUN mkdir -p /app/tmp/sockets
RUN mkdir -p /app/tmp/pids
CMD ["bundle", "exec", "puma", "-b", "unix:///app/tmp/sockets/puma.sock"]