name: ci
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  execute_ci:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: "./docker-compose.yml"
      - name: Setup test env
        run: "docker compose exec -T app bin/setup_test_env"
      - name: Run ci
        run: "docker compose exec -T app bin/ci"
    